### PR TITLE
SuperHeroInfo component

### PR DESCRIPTION
**Pull request by novenexus**
SuperHeroInfo component. Information box to be displayed on the start page instead of search bar if you have selected a hero on the superhero page.

### CODE REVIEW

**Review by Moraxan — CHANGES_REQUESTED** [review]
There is still work to be done on the css.

The yellow boxes need rounded borders and outlines, as an example.
The hero text could be left aligned and the stats boxes aren't using the same margin as the other elements.

**Review by Chab93 — DISMISSED** [review]
Nice job, I think the hero info looks cool. Maybe for next sprint we can make it a little bit slimmer by hiding / truncating stuff, not sure what but let's talk about it on the meeting :D

One thing that needs attention before merge however, the css seems to break somewhere but I can't see what it is. When Matches are below 3, so 1 or 2 the cards are showing like this:

image

And when 3 or more the matches + sort components are not spread like before, they are now centered:

image

When the CSS issue is resolved I think this one is done and ready for merge :)

**Review by Moraxan — APPROVED** [review]
The changes I suggested are sorted.

Well done!

**Review by daniellangton91 — APPROVED** [review]
After minor changes it seems fine to merge! Good job with the page!

**Pull request merged**
