### PR TITLE
Calle modalsnimage

### PR DESCRIPTION
**Pull request by Moraxan**
Fixed so that we can now press enter to do a fetch when in free search and on the desktop.

Added a rudimentary profiles page with a proper route. Also made ground work for it to take a variable from local storage and process it. At the moment it uses the 3 dummy recipes from the start page to have something to display.

Fiddeled around with the Backbutton. It still works as intended if not better, since it now goes back one page, but... If I click a recipe on the Profile Page and click back. The back button doesn't re render on the profile page. Very odd.

### CODE REVIEW

**Review by Chab93 — APPROVED** [review]
Works. as you say we need to take another look at back button.
Adjusted so there is no additional stroke applied to cards on profile page.

**Review by Chab93 — CHANGES_REQUESTED** [review]
Jag har lyckats göra något dumt, får kolla efter demo

**Review by Chab93 — APPROVED** [review]
Checked with Calle and tested my unintentional merge to this branch... works good now.
However this was not my intention... :)

**Review by MartinaSellden — APPROVED** [review]
Great job! As of now the back-button on recipe page doesn't go back to profile when you go from profile to recipe and click the button to go back, but we can look at that at a later stage.

**Pull request merged**
