### PR TITLE
Daniel final css

### PR DESCRIPTION
**Pull request by daniellangton91**
This is a major update of the site's CSS. Too many changes to list here.
Make sure that you test everything in mobile version as well.

### CODE REVIEW

**Review by Moraxan — CHANGES_REQUESTED** [review]
Something's off with the hero page. When a hero is selected and the recipes are displayed then aren't scrollable all the way and are hidden by the footer. This is in desktop.

Had to do a pull. That solved it.

**Review by Moraxan — CHANGES_REQUESTED** [review]
Something's off with the hero page. When a hero is selected and the recipes are displayed then aren't scrollable all the way and are hidden by the footer. This is in desktop

Didn't have the latest commit when testing the branch. Everything is in order.

**Review by Moraxan — APPROVED** [review]
Everything works! Well done!

**Review by Chab93 — APPROVED** [review]
With the latest commits I find this working good on my end. Really good job! :)

Maybe wait with merge in case more members can test?

**Review by Klebert-01 — APPROVED** [review]
Everything looks perfect!

**Pull request merged**
