### PR TITLE
added more button

### PR DESCRIPTION
**Pull request by Pradarsh**
Added more button and able to scroll through receips.

### CODE REVIEW

**Review by Chab93 — CHANGES_REQUESTED** [review]
Function not in a working state.

The idea was to get all results back when you search say at a cap of 50 - 100 results.
Initially we only view 6 results but you can click show more to display them all.

There are some issues with the offset parameter, the biggest one is that ingredient search (MTVMH) does not even have it so website is not consistent, and it requires multiple fetches to view additional data.

Also I see in the getApiData() function the results are appended all the time to the existing array: createCards([...recipesST, ...result.results]);
This makes the result list only to grow larger instead of reset if you make a new search.

I think a more general solution could be to have some ternary / condition in the rendering that if results is < 7 you display all results. if result is > 6 you display 6 cards and the show more button that can display them all. This would work in the same manner for both type of searches and not require any appending in the getApiData.

**Comment by Pradarsh** [comment]
@Chab93  I have made the changes according to my understanding please review it again and let me know if any changes are required.

**Review by Chab93 — CHANGES_REQUESTED** [review]
Hi Prabha,

Not really what I meant, I will try to rephrase.
isMore is not needed.

The idea is you only fetch once with getApiData().

- You make a search, say you get back 18 results.
- You could then have a function that divides the result in 2 arrays, for example:
- let firstSix = [];
- let theRest = [];

In the function you add the first 6 recipes to the firstSix array with a for loop and the rest of the recipes to the theRest array in the same loop:

      let firstSix = [];
      let theRest = [];

      for(let i = 0; i < recipes.length; i++){
        if(i < 6){
          firstSix[i] = recipes[i];
        }
        else{
          theRest[i - 6] = recipes[i];
        }
      }

in this functions return you can then by default return firstSix array + show the button to display more. if button is clicked you also display theRest array and hide button. This could be controlled by a useState bool.

Example:

**state declared outside of function:**
const [showMore, setShowMore] = useState(false);

**Function return:**
return (
<>
    {firstSix.map((recipe) => (<Card />)}
    {!showMore && <BUTTON onClick={() => {setShowMore(true)]}>}
    {showMore && theRest.map((recipe) => (<Card />)}
</>
)


The idea is that above function could be used in our primary return that exists today in a ternary. if recipes is less then 7 you simply map them as is right now. If more then 6 you call this new function example above to display first 6 recipes + show more button that will trigger the rest if clicked.

Good idea if above is used to add setShowMore(false) in the getApiData so button is visible on next search.


I hope this makes sense, hard to describe this much logic in a small GitHub window.... :)

If unclear please contact me on teams instead and I'll show you.

**Comment by Pradarsh** [comment]
@Chab93 so i need to main four states here: firstSixRecipesST, firstSIxRecipesMTVMH, restRecipesST, restRecipesMTVMH ? and currently there is maxHits which is 6 which means i get only 6 results at a time from api response should i increase that 18 ?

**Comment by Moraxan** [comment]
"and currently there is maxHits which is 6 which means i get only 6 results at a time from api response should i increase that 18 ?"
 
 You can change the number to what ever you desire if you click the hamburger button and chose setting. Your choices are stored locally.
 
 You don't have to fetch 18 recipies. You can use the the 3 development recipies. Just show one 1 as default and the 2 others when you press show more. 
 
Seems odd that you'd have to lift out 6 parameters. Should be a simpler solution. Christian suggested using an array that is populated with the searches.

**Comment by Pradarsh** [comment]
@Chab93  made the suggested changes can you let me know if it is correct or not ?

**Review by Chab93 — APPROVED** [review]
Nice job, to me this now works as expected :)

**Review by Moraxan — APPROVED** [review]
This works as intended as far as I can see.

**Pull request merged**
